// Code generated by codegen/run; DO NOT EDIT
package dev.naoh.lettucef.api.commands

import dev.naoh.lettucef.api.models._
import io.lettuce.core.FlushMode


trait ScriptingCommandsF[F[_], K, V] {

  def eval(script: String, keys: Seq[K], values: Seq[V]): F[RedisData[V]]
  
  def eval(script: Array[Byte], keys: Seq[K], values: Seq[V]): F[RedisData[V]]
  
  def evalReadOnly(script: Array[Byte], keys: Seq[K], values: Seq[V]): F[RedisData[V]]
  
  def evalsha(digest: String, keys: Seq[K], values: Seq[V]): F[RedisData[V]]
  
  def evalshaReadOnly(digest: String, keys: Seq[K], values: Seq[V]): F[RedisData[V]]
  
  def scriptExists(digests: String*): F[Seq[Boolean]]
  
  def scriptFlush(): F[String]
  
  def scriptFlush(flushMode: FlushMode): F[String]
  
  def scriptKill(): F[String]
  
  def scriptLoad(script: String): F[String]
  
  def scriptLoad(script: Array[Byte]): F[String]
  
}
